# Site settings
title: Let's Make
description: "The home-page of Let's Make, a technology, crafts and education group based in Brighton UK"
url: "http://letsmake-uk.github.io/letsmake-uk/"
author:
  name: "N. Seymour-Smith and L. d'Aboville"
  url: "http://letsmake-uk.github.io/letsmake-uk/"

# Links
makerlab: "http://makerclub.org/makerlab"
galileo: "http://letsmake-uk.github.io/sound-light-and-motion"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
